name: Build & Deploy Multi-App to Amazon ECR & ECS

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPO_NAME: ${{ vars.ECR_REPO_NAME }} # Base name, e.g. "my-app"

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Configure AWS credentials
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ${{ env.AWS_REGION }}

    # Step 3: Login to Amazon ECR
    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v2

    # Step 4: Set ECR base URI
    - name: Set ECR repo base
      run: echo "ECR_BASE=${{ steps.login-ecr.outputs.registry }}" >> $GITHUB_ENV

    - name: Set ECR repo name
      run: echo "ECR_REPO_NAME=${{ vars.ECR_REPO_NAME }}" >> $GITHUB_ENV

    # Step 5: Build and push both apps
    - name: Build and push Docker images for s3-app and sqs-app
      run: |
        for APP in s3-app sqs-app; do
          IMAGE_URI="${ECR_BASE}/${ECR_REPO_NAME}-${APP}"
          echo "Building $APP -> $IMAGE_URI"

          docker build -t ${IMAGE_URI}:latest -t ${IMAGE_URI}:${GITHUB_SHA} ./application/${APP}
          docker push ${IMAGE_URI}:latest
          docker push ${IMAGE_URI}:${GITHUB_SHA}
        done
      env:
        ECR_BASE: ${{ env.ECR_BASE }}
        ECR_REPO_NAME: ${{ env.ECR_REPO_NAME }}

    # # Step 6: Setup Terraform
    # - name: Setup Terraform
    #   uses: hashicorp/setup-terraform@v2

    # # Step 7: Terraform Init
    # - name: Terraform Init
    #   working-directory: ./terraform/stage2-ecs
    #   run: terraform init

    # # Step 8: Terraform Plan with both app image URIs
    # - name: Terraform Plan
    #   working-directory: ./terraform/stage2-ecs
    #   run: |
    #     terraform plan \
    #       -var="s3_app_image=${{ env.ECR_BASE }}/${{ env.ECR_REPO_NAME }}-s3-app:${{ github.sha }}" \
    #       -var="sqs_app_image=${{ env.ECR_BASE }}/${{ env.ECR_REPO_NAME }}-sqs-app:${{ github.sha }}" \
    #       -out=tfplan

    # # Step 9: Terraform Apply
    # - name: Terraform Apply
    #   working-directory: ./terraform/stage2-ecs
    #   run: terraform apply -auto-approve tfplan