name: Base Infra

on:
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  ECR_REPO_NAME: ${{ vars.ECR_REPO_NAME }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  # -----------------------------------
  # Stage 1: Provision base infrastructure
  # -----------------------------------
  infra:
    name: Provision Infra
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./terraform/stage1-infra
    steps:
      - uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2

      - name: Terraform Init & Apply
        run: |
          terraform init
          terraform apply -auto-approve
